# Copyright 2018-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id      = "org.cloudfoundry.azureapplicationinsights"
name    = "Cloud Foundry Azure Application Insights Buildpack"
version = "1.0.0-RC04"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.dependencies]]
id      = "azure-application-insights-java"
name    = "Azure Application Insights Java Agent"
version = "2.4.1"
uri     = "https://github.com/Microsoft/ApplicationInsights-Java/releases/download/2.4.1/applicationinsights-agent-2.4.1.jar"
sha256  = "ee52f957f05e1cf904ac0e251cde88eec5cbc57294b58a630a1e888620589cdc"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "MIT"
  uri  = "https://github.com/Microsoft/ApplicationInsights-Java/blob/master/LICENSE.txt"

[metadata]
pre_package   = "ci/build.sh"
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "AI-Agent.xml",
  "bin/build",
  "bin/detect",
  "bin/azure-application-insights-properties",
  "buildpack.toml",
]
